POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3BlX3ZhYXJhbWEiLCJpZCI6IjY1MDk5ZDBlMGRiZTRlOTc4NjA2MGM0MiIsImlhdCI6MTY5NTIwMDc2Mn0.LCMO2NL-InxXpmr7uBAraug3DgsRMja1iKLkH3APTMk

{
    "title": "Testi3",
    "author": "Testaaja3",
    "url": "www.testi2.fi",
    "likes": 1,
    }